local set = require('editor_scripting/keymaps').set
local telescope = require('editor_scripting.telescope_extensions')

set("Go to declaration", 'n', '<leader>cD', '<cmd>lua vim.lsp.buf.declaration()<CR>')
set("Go to definition", 'n', '<leader>cd', '<cmd>lua vim.lsp.buf.definition()<CR>')
set("Hover documentation", 'n', '<leader>ch', '<cmd>lua vim.lsp.buf.hover()<CR>')
set("Go to implementation", 'n', '<leader>ci', '<cmd>lua vim.lsp.buf.implementation()<CR>')
set("Signature help", 'n', '<leader>cz', '<cmd>lua vim.lsp.buf.signature_help()<CR>')
set("Workspace diagnostics", 'n', '<leader>cAA', [[:Telescope diagnostics<CR>]])
set("Line diagnostics", 'n', '<leader>cAa', [[:lua vim.diagnostic.open_float()<CR>]])
set("Add workspace folder", 'n', '<leader>cwa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>')
set("Remove workspace folder", 'n', '<leader>cwr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>')
set("List workspace folders", 'n', '<leader>cwl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>')
set("Type definition", 'n', '<leader>ct', '<cmd>lua vim.lsp.buf.type_definition()<CR>')
set("Rename", 'n', '<leader>cR', '<cmd>lua vim.lsp.buf.rename()<CR>')
set("Code action", 'n', '<leader>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>')
set("References", 'n', '<leader>cr', '<cmd>lua vim.lsp.buf.references()<CR>')
set("Format buffer", 'n', '<leader>cF', '<cmd>lua vim.lsp.buf.format { async = true }<CR>')
set("Search types (current)", 'n', '<leader>cft', function() telescope.fuzzy_search_types(true) end)
set("Search functions (current)", 'n', '<leader>cff', function() telescope.fuzzy_search_functions(true) end)
set("Search types (workspace)", 'n', '<leader>cfT', function() telescope.fuzzy_search_types(false) end)
set("Search functions (workspace)", 'n', '<leader>cfF', function() telescope.fuzzy_search_functions(false) end)
