local map = require('editor_scripting/keymaps').set

map("Focus next window", 'n', '<leader>ww', '<C-W>w')
map("Focus previous window", 'n', '<leader>wW', '<C-W>W')
map("Split window horizontally", 'n', '<leader>ws', '<C-W>s')
map("Split window vertically", 'n', '<leader>wv', '<C-W>v')
map("Focus left window", 'n', '<leader>wh', '<C-W>h')
map("Focus down window", 'n', '<leader>wj', '<C-W>j')
map("Focus up window", 'n', '<leader>wk', '<C-W>k')
map("Focus right window", 'n', '<leader>wl', '<C-W>l')
map("Equalize window sizes", 'n', '<leader>w=', '<C-W>=')
map("Close window", 'n', '<leader>wq', '<C-W>q')
map("Quit all", 'n', '<leader>wQ', ':qa<cr>')
map("Resize window left", 'n', '<leader>wxh', '<C-W>5<')
map("Resize window down", 'n', '<leader>wxj', ':resize +5<cr>')
map("Resize window up", 'n', '<leader>wxk', ':resize -5<cr>')
map("Resize window right", 'n', '<leader>wxl', '<C-W>5>')
map("Move window left", 'n', '<leader>wmh', '<C-W>H')
map("Move window down", 'n', '<leader>wmj', '<C-W>J')
map("Move window up", 'n', '<leader>wmk', '<C-W>K')
map("Move window right", 'n', '<leader>wml', '<C-W>L')
