local map = require('editor_scripting/keybindings').map

map("Go to declaration", 'n', '<leader>cD', '<cmd>lua vim.lsp.buf.declaration()<CR>')
map("Go to definition", 'n', '<leader>cd', '<cmd>lua vim.lsp.buf.definition()<CR>')
map("Hover documentation", 'n', '<leader>ch', '<cmd>lua vim.lsp.buf.hover()<CR>')
map("Go to implementation", 'n', '<leader>ci', '<cmd>lua vim.lsp.buf.implementation()<CR>')
map("Signature help", 'n', '<leader>cz', '<cmd>lua vim.lsp.buf.signature_help()<CR>')
map("Workspace diagnostics", 'n', '<leader>cAA', [[:Telescope diagnostics<CR>]])
map("Line diagnostics", 'n', '<leader>cAa', [[:lua vim.diagnostic.open_float()<CR>]])
map("Add workspace folder", 'n', '<leader>cwa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>')
map("Remove workspace folder", 'n', '<leader>cwr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>')
map("List workspace folders", 'n', '<leader>cwl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>')
map("Type definition", 'n', '<leader>ct', '<cmd>lua vim.lsp.buf.type_definition()<CR>')
map("Rename", 'n', '<leader>cR', '<cmd>lua vim.lsp.buf.rename()<CR>')
map("Code action", 'n', '<leader>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>')
map("References", 'n', '<leader>cr', '<cmd>lua vim.lsp.buf.references()<CR>')
map("Format buffer", 'n', '<leader>cF', '<cmd>lua vim.lsp.buf.format { async = true }<CR>')
map("Search types (current)", 'n', '<leader>cft', '<cmd>lua Seek_types(true)<CR>')
map("Search functions (current)", 'n', '<leader>cff', '<cmd>lua Seek_functions(true)<CR>')
map("Search types (workspace)", 'n', '<leader>cfT', '<cmd>lua Seek_types(false)<CR>')
map("Search functions (workspace)", 'n', '<leader>cfF', '<cmd>lua Seek_functions(false)<CR>')
